name: SE-adLIF

channels:
  - defaults
  - pytorch
  - conda-forge
  - nvidia

dependencies:
  - pip
  - python=3.11.8
  - pytorch==2.1.2
  - pytorch-cuda==12.1
  - torchaudio==2.1.2
  - pytorch-lightning==2.2.1
  - pip:
      - hydra_core==1.3.2
      - scipy==1.12.0
      - tonic==1.4.3
      - matplotlib